### ISSUE TITLE
Visual studio code

### ISSUE THREAD

**Issue by MarcioAmadeus** [siecola/WebAPIBook#1]
Bom dia,
Eu estou lendo seu livro. Eu consigo usar o visual studio code pra fazer todos os exemplos do livro ? Eu uso mac

**Comment by siecola** [comment]
Bom dia Márcio,

Infelizmente com o Visual Studio Code não é possível. Porém, já existe o Visual Studio Community para Mac, mas eu ainda não testei com os exemplos do livro.

Obrigado.
